name: DevSecOps Pipeline PAI4

on:
  push:
    branches: ["master", "main"]

jobs:
  # ---------------------------------------------------
  # TAREA DEV 3: Análisis de Infraestructura (IaC)
  # ---------------------------------------------------
  iac_scan_trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v3

      - name: Escaneo IaC con Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-ref: "."
          format: "json"
          output: "trivy-iac-report.json"

      - name: Guardar reporte Trivy
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-report
          path: trivy-iac-report.json

  # ---------------------------------------------------
  # TAREA DEV 3: Análisis Dinámico (DAST)
  # ---------------------------------------------------
  dast_scan_zap:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Levantar la aplicación DefectDojo
        run: |
          docker compose up -d
          echo "Esperando a que DefectDojo inicie sus servicios..."
          sleep 120

      - name: Ejecutar OWASP ZAP (Baseline Scan)
        run: |
          docker run --network host -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://localhost:8080 \
            -J zap-dast-report.json || true

      - name: Apagar DefectDojo
        run: docker compose down

      - name: Guardar reporte ZAP
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: zap-report
          path: zap-dast-report.json
